---

# check_root
- name: Check supported OS
  fail:
    msg: Unsupported OS
  when:
    - ansible_distribution!="Ubuntu" and ansible_distribution_version!="14.04"
    - ansible_distribution!="Ubuntu" and ansible_distribution_version!="16.04"
    - ansible_distribution!="Ubuntu" and ansible_distribution_version!="18.04"
    - ansible_distribution=="Debian" and ansible_distribution_version=="8"
    - ansible_distribution=="Debian" and ansible_distribution_version=="9"
    - ansible_distribution=="Debian" and ansible_distribution_version=="10"

- name: Check architecture
  fail:
    msg: "Architecture not supported {{ ansible_architecture }}"
  when: ansible_architecture not in ['x86_64', 'ppc64le', 'armv7l', 'aarch64']

- name: Install CA certificates
  apt:
    name: ca-certificates
    state: present
