---

# - name: Template run script
#   template:
#     src: run-installer.sh
#     dest: /run.sh
#     mode: u+rwx

- name: Install
  # shell: /run.sh
  command: "php {{ installer_file }} --hostname-fqdn={{ hostname }} --admin-username={{ admin_username }} --admin-password={{ admin_password }} --admin-email={{ admin_email }} --non-interactive --no-reboot"
  async: "{{ installer_timeout }}" # seconds
  poll: 5
  register: installer

# - name: Clean up
#   file:
#     path: /run.sh
#     state: absent

- debug:
    msg: "{{ installer.stdout.split('\n') }}"